# Configuration for Devsite to Hugo Converter

# Docsy Theme Configuration
source_repo:
  owner: "alan707"
  name: "bazel-docs"
  branch: "main"

# Hugo site settings
hugo:
  title: "Bazel Documentation"
  description: "Bazel Documentation in an easy to navigate format"
  baseURL: "https://bazel-docs-68tmf.ondigitalocean.app/"
  languageCode: "en-us"
  theme: "docsy"
  
content_mapping:
  # set 'enable_category_indices' to true to generate _index.md files for categories
  # also necessary to enable category menus in Sidebar
  # When set to false it shows a monolithic list of all pages
  # under the 'docs' menu item
  enable_category_indices: false
  tutorials:
    type: "docs"
    weight: 1
    category: "tutorials"
  start:
    type: "docs"
    weight: 2
    category: "tutorials"
  basics:
    type: "docs"
    weight: 3
    category: "tutorials"
  install:
    type: "docs"
    weight: 1
    category: "how-to-guides"
  configure:
    type: "docs"
    weight: 2
    category: "how-to-guides"
  build:
    type: "docs"
    weight: 3
    category: "how-to-guides"
  run:
    type: "docs"
    weight: 4
    category: "how-to-guides"
  remote:
    type: "docs"
    weight: 5
    category: "how-to-guides"
  migrate:
    type: "docs"
    weight: 6
    category: "how-to-guides"
  rules:
    type: "docs"
    weight: 7
    category: "how-to-guides"
  docs:
    type: "docs"
    weight: 8
    category: "how-to-guides"
  brand:
    type: "docs"
    weight: 9
    category: "how-to-guides"
  concepts:
    type: "docs"
    weight: 1
    category: "explanations"
  extending:
    type: "docs"
    weight: 2
    category: "explanations"
  external:
    type: "docs"
    weight: 3
    category: "explanations"
  about:
    type: "docs"
    weight: 4
    category: "explanations"
  community:
    type: "docs"
    weight: 5
    category: "explanations"
  contribute:
    type: "docs"
    weight: 6
    category: "explanations"
  release:
    type: "docs"
    weight: 7
    category: "explanations"
  reference:
    type: "docs"
    weight: 1
    category: "reference"
  query:
    type: "docs"
    weight: 2
    category: "reference"
  versions:
    type: "docs"
    weight: 3
    category: "reference"
  advanced:
    type: "docs"
    weight: 4
    category: "reference"

# CSS conversion settings
css_conversion:
  convert_to_scss: true
  preserve_custom_properties: true
  minify: false

# GitHub Actions settings
github_actions:
  listener_workflow_name: "bazel-listener"
  generator_workflow_name: "hugo-site-generator"
  dispatch_event_type: "bazel-docs-updated"

# Logging settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Conversion settings
conversion:
  preserve_original_structure: false
  generate_toc: true
  convert_internal_links: true
  validate_links: true
  
# File patterns to include/exclude
file_patterns:
  include:
    - "*.md"
    - "*.yaml"
    - "*.yml"
    - "*.css"
    - "*.png"
    - "*.jpg"
    - "*.jpeg"
    - "*.gif"
    - "*.svg"
  exclude:
    - "BUILD*"
    - "*.bazel"
    - "*.bzl"
    - ".git/**"
    - "node_modules/**"

# Used to automatically detect language for code blocks without explicit language identifiers
code_language_patterns:
  starlark:
    - "cc_binary("
    - "cc_library("
    - "java_library("
    - "py_binary("
    - "py_library("
    - "load("
    - "BUILD"
    - "WORKSPACE"
    - "bazel-"
    - "name ="
    - "srcs ="
    - "deps ="
    - "cc_toolchain("
    - "toolchain("
    - "filegroup("
    - "exports_files("
  bash:
    - "bazel "
    - "bazel help"
    - "bazel build"
    - "bazel test"
    - "bazel run"
    - "bazel query"
    - "#!/bin/bash"
    - "#!/bin/sh"
    - "echo "
    - "export "
    - "source "
    - "$("
    - "${"
    - "$"
    - "npm "
    - "yarn "
    - "git "
    - "cd "
    - "mkdir "
    - "rm "
    - "cp "
  python:
    - "def "
    - "class "
    - "import "
    - "from "
    - "print("
    - "__init__"
    - "self."
    - "@"
    - "lambda "
    - "return "
    - "if __name__"
    - "try:"
    - "except:"
  cpp:
    - "#include"
    - "int main"
    - "std::"
    - "namespace "
    - "cout <<"
    - "void "
    - "template<"
    - "nullptr"
    - ".cc"
    - ".cpp"
    - ".h"
    - "cin >>"
    - "using namespace"
    - "printf("
    - "scanf("
  java:
    - "public class"
    - "private "
    - "protected "
    - "import java"
    - "package "
    - "extends "
    - "implements "
    - "@Override"
    - "System.out.println"
    - "new "
    - "throw new"
    - "catch ("
  javascript:
    - "function "
    - "const "
    - "let "
    - "var "
    - "=>"
    - "console.log"
    - "require("
    - "export "
    - "import "
    - "async "
    - "await "
    - "document."
    - "window."
    - "addEventListener"
  typescript:
    - "interface "
    - "type "
    - ": string"
    - ": number"
    - ": boolean"
    - "enum "
    - "readonly "
    - "as "
  yaml:
    - "name:"
    - "type:"
    - "- name:"
    - "kind:"
    - "apiVersion:"
    - "metadata:"
    - "spec:"
  json:
    - '{"'
    - '":'
    - '": '
    - '['
    - '],'  
  xml:
    - "<?xml"
    - "<"
    - "/>"
    - "xmlns"
  html:
    - "<!DOCTYPE"
    - "<html"
    - "<body"
    - "<div"
    - "<span"
    - "<p>"
    - "<h1"
  css:
    - "body {"
    - "div {"
    - ".class"
    - "#id"
    - "color:"
    - "background:"
    - "@media"
  sql:
    - "SELECT "
    - "FROM "
    - "WHERE "
    - "INSERT INTO"
    - "UPDATE "
    - "DELETE FROM"
    - "CREATE TABLE"
    - "DROP TABLE"