name: Update docs from Bazel repo main branch
on:
  repository_dispatch:
    types: [on-bazel-trigger]
jobs:
  deploy:
    uses: ./.github/workflows/run-codegen.yml
    with:
      bazelCommitHash: ${{ github.event.client_payload.commitHash }}
      secrets: inherit
